from time import sleep

print("\033[1;34;1m{:<31}==============".format(""))
sleep(0.5)
print("{:<28}=={:<16}==".format("",""))
sleep(0.5)
print("{:<26}=={:<20}==".format("",""))
sleep(0.5)
print("{:<24}=={:<24}==".format("",""))
sleep(0.5)
print("{:<11}============={:<28}==============".format("",""))
sleep(0.5)
print("{:<10}={:<55}=".format("",""))
sleep(0.5)
print("{:<10}={:<56}=".format("",""))
sleep(0.5)
print("{:<10}=        ==={:<34}===        =".format("",""))
sleep(0.5)
print("{:<10}=      =     ={:<30}=     =      =".format("",""))
sleep(0.5)
print("{:<11}==== =       = ========================== =       = ====".format(""))
sleep(0.5)
print("{:<17}=     ={:<30}=     =".format("",""))
sleep(0.5)
print("{:<19}==={:<34}===".format("",""))
sleep(1.5)
print("{:<35}CarHub \033[0m".format(""))


